const genres = ['Jazz',
  'Funk',
  'Blues',
  'Pop',
  'Rock',
  'Hard rock',
  'Classique',
  'Country',
  'Reggae',
  'Ambient',
  'Ballade',
  'Cinematic',
  'Drum n bass',
  'Easy listening',
  'Electro',
  'Epic trailer',
  'Folk',
  'Hip-hop',
  'Latin',
  'Metal',
  'Orchestral',
  'World music',]
const moods = [
  'Action / Sports',
  'Adventure / Discovery',
  'Aggressive',
  'Comedy / Funny',
  'Crime / Triller /Spy',
  'Dark / Samber',
  'Epic /orchestral',
  'Fashion / Lifestyle',
  'Feel Good',
  'Gentle / Light',
  'Happy / Cheerful',
]
const artists = ['jeff', 'olive']
/*
const bpm = [
  'Slow',
  'Slow medium',
  'Medium',
  'Medium hight',
  'Hight',
]
*/
const bpm = [
  {name:'Slow', value:'(0-50)'},
  {name:'Slow medium', value:'(50-100)'},
  {name:'Medium', value:'(100-150)'},
  {name:'Medium hight', value:'(150-200)'},
  {name:'Hight', value:'(200 +)'},
]

const instruments = [
  'Accordion',
  'Bagpipes',
  'Banjo',
  'Bassoon',
  'Cello',
  'Clarinet',
  'Cymbal',
  'Double bass',
  'Drum',
  'Bass drum',
  'Bongo drum',
  'Snare drum',
  'Timpani',
  'Dulcimer',
  'Flute',
  'French horn',
  'Gong',
  'Guitar',
  'Electric guitar',
  'Harp',
  'Harpsichord',
  'Hurdy gurdy',
  'Jew s harp',
  'Lute',
  'Lyre',
  'Marimba',
  'Oboe',
  'Organ',
  'Pan pipes',
  'Pennywhistle',
  'Piano',
  'Recorder',
  'Saxophone',
  'Sitar',
  'Synthesizer',
  'Tambourine',
  'Triangle',
  'Trombone',
  'Trumpet',
  'Tuba',
  'Viola',
  'Violin',
  'Fiddle',
  'Xylophone',
]

export {
    genres,
    moods,
    artists,
    instruments,
    bpm,
}