const genres = ['Jazz',
  'Funk',
  'Blues',
  'Pop',
  'Rock',
  'Hard rock',
  'Classique',
  'Country',
  'Reggae',
  'Ambient',
  'Ballade',
  'Cinematic',
  'Drum n bass',
  'Easy listening',
  'Electro',
  'Epic trailer',
  'Folk',
  'Hip-hop',
  'Latin',
  'Metal',
  'Orchestral',
  'World music',]
const moods = [
  'Action / Sports',
  'Adventure / Discovery',
  'Aggressive',
  'Comedy / Funny',
  'Crime / Triller /Spy',
  'Dark / Samber',
  'Epic /orchestral',
  'Fashion / Lifestyle',
  'Feel Good',
  'Gentle / Light',
  'Happy / Cheerful',
]
const artists = ['jeff', 'olive']
/*
const bpm = [
  'Slow',
  'Slow medium',
  'Medium',
  'Medium hight',
  'Hight',
]
*/
const bpm = [
  { name: 'Slow', value: '(0-50)' },
  { name: 'Slow medium', value: '(50-100)' },
  { name: 'Medium', value: '(100-150)' },
  { name: 'Medium hight', value: '(150-200)' },
  { name: 'Hight', value: '(200 +)' },
]

const instruments = [
  'Accordion',
  'Bagpipes',
  'Banjo',
  'Bassoon',
  'Cello',
  'Clarinet',
  'Cymbal',
  'Double bass',
  'Drum',
  'Bass drum',
  'Bongo drum',
  'Snare drum',
  'Timpani',
  'Dulcimer',
  'Flute',
  'French horn',
  'Gong',
  'Guitar',
  'Electric guitar',
  'Harp',
  'Harpsichord',
  'Hurdy gurdy',
  'Jew s harp',
  'Lute',
  'Lyre',
  'Marimba',
  'Oboe',
  'Organ',
  'Pan pipes',
  'Pennywhistle',
  'Piano',
  'Recorder',
  'Saxophone',
  'Sitar',
  'Synthesizer',
  'Tambourine',
  'Triangle',
  'Trombone',
  'Trumpet',
  'Tuba',
  'Viola',
  'Violin',
  'Fiddle',
  'Xylophone',
]

const composers = [
  'A.del',
  'Ruskov',
  'Mathieu',
  'Pierre Marie',
  'Elliot Dahan',
  'Davy and Yoann',
  'Mika P',
  'Patrice Dangelo',
  'Lionel',
  'Fred Shumann',
  'Thomas Z',
  'Junior Lewis',
  'Illias P',
  'Leroy Q',
  'Franck Luccini',
  'Mike Buyens',
  'Gilles P',
  'Geoff',
  'Rodolphe Andrieu',
  'Thomas Nils',
  'Harry',
  'jeff'
]

const fakeComposers = [
  "https://randomuser.me/api/portraits/women/48.jpg",
  "https://randomuser.me/api/portraits/men/56.jpg",
  "https://randomuser.me/api/portraits/women/23.jpg",
  "https://randomuser.me/api/portraits/women/51.jpg",
  "https://randomuser.me/api/portraits/men/74.jpg",
  "https://randomuser.me/api/portraits/men/56.jpg",
  "https://randomuser.me/api/portraits/men/34.jpg",
  "https://randomuser.me/api/portraits/women/87.jpg",
  "https://randomuser.me/api/portraits/women/76.jpg",
  "https://randomuser.me/api/portraits/men/71.jpg",
  "https://randomuser.me/api/portraits/women/30.jpg",
  "https://randomuser.me/api/portraits/women/42.jpg",
  "https://randomuser.me/api/portraits/women/19.jpg",
  "https://randomuser.me/api/portraits/men/42.jpg",
  "https://randomuser.me/api/portraits/women/63.jpg",
  "https://randomuser.me/api/portraits/men/80.jpg",
  "https://randomuser.me/api/portraits/women/23.jpg",
  "https://randomuser.me/api/portraits/women/49.jpg",
  "https://randomuser.me/api/portraits/men/67.jpg",
  "https://randomuser.me/api/portraits/women/90.jpg",
  "https://randomuser.me/api/portraits/women/29.jpg",
]

export {
  genres,
  moods,
  artists,
  instruments,
  bpm,
  composers,
  fakeComposers,
}